#datasource setting
spring:
  datasource:
    url: jdbc:p6spy:mysql://lghcode.cn:3306/janeBook?characterEncoding=utf-8&useSSL=false
    username: root
    password: Lgh/Lgh123
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
#log
logging:
  level:
    com.lghcode.briefbook: debug

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

#oss
oss:
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAItTfvXFdSEtAT #AccessKey
  accessKeySecret: ZFudNKdhnkJcaTYq1QjuYPQ0e4HZZD  #Accesssecret
  bucketName: lgh-chat-im # bucket名称
  filePath: briefBook    #bucket下文件夹的路径
  domain: lgh-chat-im.oss-cn-hangzhou.aliyuncs.com #文件访问域名前缀