#datasource setting
spring:
  datasource:
    url: jdbc:p6spy:mysql://lghcode.cn:3306/janeBook?characterEncoding=utf-8&useSSL=false
    username: root
    password: Lgh/Lgh123
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
#log
logging:
  level:
    com.lghcode.briefbook: debug

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml