#datasource setting
spring:
  datasource:
    url: jdbc:p6spy:mysql://lghcode.cn:3306/janeBook?characterEncoding=utf-8&useSSL=false
    username: root
    password: Lgh/Lgh123
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
#log
logging:
  level:
    com.lghcode.briefbook: debug

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

#oss
oss:
  endpoint: http://oss-cn-hangzhou.aliyuncs.com #节点域名
  accessKeyId: LTAItTfvXFdSEtAT #AccessKey
  accessKeySecret: ZFudNKdhnkJcaTYq1QjuYPQ0e4HZZD  #Accesssecret
  bucketName: lgh-chat-im # bucket名称
  filePath: briefBook    #bucket下文件夹的路径
  domain: lgh-chat-im.oss-cn-hangzhou.aliyuncs.com #文件访问域名前缀

#tencent sms
tencent:
  sms:
    secretId: AKIDPeiX6QuzJNBlD67Xw97csu7VeYMxDchW #腾讯云账户密钥对id
    secretKey: tZ07cqoW31lETUt2vRinb9a2E91iHagR #腾讯云账户密钥对key
    sdkAppId: 1400411815  #应用appId
    sign: 亮桂港佳伟  #短信签名内容
    loginTemplateId: 686990  #登录短信模板id
    upPwdTemplateId: 687434  #重置密码短信模板id