#datasource setting
spring:
  datasource:
    url: jdbc:p6spy:mysql://lghcode.cn:3306/janeBook?characterEncoding=utf-8&useSSL=false
    username: root
    password: Lgh/Lgh123
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      validationQuery: SELECT 1
      stat-view-servlet:
        allow: true
  #redis
  redis:
    database: 3
    host: 119.23.225.92
    port: 6379
    password: lghcode
    timeout: 0
    lettuce:
      pool:
        max-active: 30
        max-wait: 5000
        max-idle: 10
        min-idle: 2

#log
logging:
  level:
    com.lghcode.briefbook: debug

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

#oss
oss:
  endpoint: http://oss-cn-hangzhou.aliyuncs.com #节点域名
  accessKeyId: OlRMCbIhI4P/M1Qx7nQKMQQpryRuYzWxSUbJR07W6W0= #加密后的AccessKey
  accessKeySecret: U/nZyKhCqF44ms6ZgClRFS5igSvWIPYx6+uvUtnQTvQ=  #加密后的Accesssecret
  bucketName: lgh-chat-im # bucket名称
  filePath: briefBook    #bucket下文件夹的路径
  domain: lgh-chat-im.oss-cn-hangzhou.aliyuncs.com #文件访问域名前缀

#tencent sms
tencent:
  sms:
    secretId: UeyTK2NW56uclvogVszKzUTowJDWIUah02iKP3nvBejyqI/xZX1VTX5EJuLdP+fU #加密后的腾讯云账户密钥对id
    secretKey: cp+s1QM3WXY3PNrVvJblTlOI/pDZDhn8D3O6KkP6ADsEKa8kbmM1sUlGyUdO1ult #加密后的腾讯云账户密钥对key
    sdkAppId: 1400411815  #应用appId
    sign: 亮桂港佳伟  #短信签名内容
    loginTemplateId: 686990  #登录短信模板id
    upPwdTemplateId: 687434  #重置密码短信模板id
    upMobileTemplateId: 689748  #更换手机号短信模板id
#jwt
jwt:
  header: Authorization
  secret: defaultSecret
  expiration: 2592000
  md5Key: randomKey